--EXAMEN BASE DE DADES SIMULACRE
--2
SELECT DESCCRIP DESCRIPCIÓ, NVL(STOCK,0) STOCK, NVL(STOCK_MIN,0) STOCK_MIN,
NVL(STOCK_MIN,0) - NVL(TOCK,0) FALTEN
FROM COMPATIBILITAT.ARTICLES
WHERE NVL(STOCK,0)<NVL(STOCK_MIN,0)

--3
SELECT CODFAC, TO_CHAR(DATA,'DD - MM - YYYY') DATAFAC
FROM COMPTABILITAT.FACTURES
WHERE TO_CHAR(DAT,'MM')='03' AND_TO_CHAR(DATA,'YYYY') IN ('2021','2022','2023')
ORDER BY DATA_DESC;
--4
SELECT CODCLI CLIENT, COUNT(*) NUMFAC
FROM COMPTABILITAT.FACTURES
WHERE CODCLI BETWEEN 250 AND 300
GROUP BY CODCLI
ORDER BY NUMFAC;
--5
SELECT CODCLI CLIENT, COUNT(*) NUMFAC
FROM COMPTABILITAT.FACTURES f JOIN COMPTABILITAT.CLIENTS c on(
        F.CODCLI=C.CODCLI)
WHERE CODCLI BETWEEN 250 AND 300
GROUP BY CODCLI
ORDER BY NUMFAC;
--6
SELECT to_char(DATA,'yyyy') "any", COUNT(*) NUM
FROM COMPTABILITAT.FACTURES
GROUP BRY TO_CHAR(DAT,'yyyy')
ORDER BY 1;
--7
SELECT V.CODVEN VENEDOR, V.NOM NOM, NVL(to_char(CAP.CODVEN),'No té cap') JEFE, NVL(CAP.NOM,0) NOM_JEFE
FROM COMPTABILITA.VENEDORS V LEFT OUTER JOIN COMPTABILITAT.VENEDORS CAP ON(
    V.CODCAP=CAP.CODVEN)
ORDER BY 1;
--8
SELECT
FROM COMPTABILITAT.CLIENTS C JOIN COMPTABILITAT.POBLES P ON(
    C.CODPO=P.CODPO)
    GROUP BY C.CODPO, P.NOM
    HAVING COUNT(*)>3;
--9
SELECT CODCLI
FROM COMPTABILITAT.CLIENTS
WHERE CODCLI NOT IN(
                    SELECT CODCLI
                    FROM COMPTABILITAT.FACTURES
                    WHERE CODCLI IS NOT NULL);
--10
SELECT CODART, DESCRIP, PREU
FROM COMPTABILITAT.ARTICLES
WHERE PREU = ( SELECT MAX(preu)
                FROM COMPTABILITAT.ARTICLES);

/*
SELECT CODART, DESCRIP, PREU
FROM (SELECT CODART, DESCRIP, PREU
        FROM COMPTABILITAT.ARTICLES
        ORDER BY PREU DESC)
WHERE ROWNUM<=1;
*/
--14


